# Generated by Django 5.0.1 on 2024-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agentname',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('pollingunit_uniqueid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agentname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncedPuResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('polling_unit_uniqueid', models.CharField(max_length=200)),
                ('party_abbreviation', models.CharField(max_length=200)),
                ('party_score', models.IntegerField(blank=True, null=True)),
                ('entered_by_user', models.TextField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('user_ip_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'announced_pu_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('uniqueid', models.AutoField(primary_key=True, serialize=False)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('lga_name', models.CharField(max_length=200)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('lga_description', models.TextField(blank=True, null=True)),
                ('entered_by_user', models.CharField(max_length=200)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('user_ip_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyid', models.CharField(max_length=200)),
                ('partyname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'party',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('uniqueid', models.AutoField(primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField(blank=True, null=True)),
                ('ward_id', models.IntegerField(blank=True, null=True)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('uniquewardid', models.IntegerField(blank=True, null=True)),
                ('polling_unit_number', models.CharField(blank=True, max_length=200, null=True)),
                ('polling_unit_name', models.CharField(blank=True, max_length=200, null=True)),
                ('polling_unit_description', models.TextField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('long', models.CharField(blank=True, max_length=200, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=200, null=True)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'polling_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uniqueid', models.AutoField(primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField(blank=True, null=True)),
                ('ward_name', models.CharField(max_length=200)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('ward_description', models.TextField(blank=True, null=True)),
                ('entered_by_user', models.CharField(max_length=200)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('user_ip_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ward',
                'managed': False,
            },
        ),
    ]
